parameters:
#    i_fppo_technique.example.class: IFppo\TechniqueBundle\Example

services:
#    i_fppo_technique.example:
#        class: %i_fppo_technique.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
