parameters:
#    i_fppo_utilisateur.example.class: IFppo\UtilisateurBundle\Example

services:
#    i_fppo_utilisateur.example:
#        class: %i_fppo_utilisateur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
