imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

doctrine:    
    dbal:
      default_connection: mySql2
      connections:
          default:            
              driver:   pdo_mysql
              host:     SRV-INTRANET
              port:     null
              dbname:   fppo
              user:     jeremy
              password: denieul              
              charset:  UTF8
              # Ignore les tables qui commençant par les expressions données
              schema_filter: ~^(?!a|chacal_divers_|e|confirmation_commande_|clients_0|clients_1|clients_2|clients_3|d|e|facturation_commande_|facturation_h|g|l|m|p|s|t|u|v)~
          chacalStat:            
              driver:   pdo_sqlsrv
              host:     SRV-CHACAL\CHACAL_PROD
              port:     null
              dbname:   Chacal21
              user:     sa
              password: sommos35
              charset:  UTF8
              # Ignore les tables qui commençant par les expressions données
              schema_filter: ~^(?!sys_|tbl_C|tbl_D|tbl_F|tbl_Elevation_|tbl_I|tbl_L|tbl_P|tbl_R|tbl_S|tbl_T|tbl_V)~
          sageStat:            
              driver:   pdo_sqlsrv
              host:     SRV-SAGE\SAGE100
              port:     null
              dbname:   FPPO
              user:     sa
              password: sommos35
              charset:  UTF8
              # Ignore les tables qui commençant par les expressions données
            #  schema_filter: ~^(?!cb|DP|F_A|F_B|F_CA|F_COMPTER|F_COMPTETG|F_COMPTETM|F_COMPTETR|F_CON|F_CY|F_D|F_EBANQUEC|F_EBU|F_EC|F_EE|F_EF|F_EL|F_EM|F_EN|F_EP|F_ER|F_ES|F_ET|F_EU|F_EX|F_F|F_H|F_I|F_J|F_L|F_MODELEA|F_MODELEG|F_MON|F_N|F_O|F_PIECEA|F_PIECEG|F_PR|F_R|F_S|F_T|F_U|P_)~
              schema_filter: ~^(?!cb|DP|F_NAT)~
          mySql2:            
              driver:   pdo_mysql
              host:     SRV-INTRANET2
              port:     null
              dbname:   ifppo_test
              user:     symfony
              password: symfony
              charset:  UTF8 
              schema_filter: ~^(?!c)~
              
    orm:        
        default_entity_manager: mySql2
        entity_managers:
            default:
                auto_mapping: false
                connection:       default
                mappings:
                    IFppoCommerceBundle: ~
                    IFppoTechniqueBundle: ~
                    IFppoScanProdBundle: ~
            chacalStat:
                auto_mapping: false
                connection:       chacalStat
                mappings:
                    IFppoCommerceBundle: ~  
                    IFppoTechniqueBundle: ~
                    IFppoScanProdBundle: ~
            sageStat:
                auto_mapping: false
                connection:       sageStat
                mappings:
                    IFppoCommerceBundle: ~ 
                    IFppoTechniqueBundle: ~
                    IFppoScanProdBundle: ~
            mySql2:
                auto_mapping: false
                connection:       mySql2
                mappings:
                    IFppoCommerceBundle: ~ 
                    IFppoTechniqueBundle: ~
                    IFppoScanProdBundle: ~
ali_datatable:  
    all: 
        action:           false
        search:           false   
        
knp_snappy:
    pdf:
        enabled:    true
        binary:     'C:\wkhtmltopdf\wkhtmltopdf.exe'
        options:    []   