parameters:
#    i_fppo_scan_prod.example.class: IFppo\ScanProdBundle\Example

services:
#    i_fppo_scan_prod.example:
#        class: %i_fppo_scan_prod.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
