IFppo\CommerceBundle\Entity\FacturationCommande:
    type: entity
    table: facturation_commande
    fields:
        incrementation:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        numeroFacture:
            type: float
            nullable: false
            column: numero_facture
        numeroClient:
            type: text
            nullable: false
            column: numero_client
        nomClient:
            type: text
            nullable: false
            column: nom_client
        idCommande:
            type: float
            nullable: false
            column: id_commande
        numeroCommande:
            type: text
            nullable: false
            column: numero_commande
        reference:
            type: text
            nullable: false
        dateFacture:
            type: text
            nullable: false
            column: date_facture
        commentaire:
            type: text
            nullable: false
        reglement:
            type: text
            nullable: false
        dateImpression:
            type: text
            nullable: false
            column: date_impression
        dateEcheance:
            type: text
            nullable: false
            column: date_echeance
        proforma:
            type: integer
            unsigned: false
            nullable: false
        commandeChacal:
            type: integer
            unsigned: false
            nullable: false
            column: commande_chacal
        montantTotalHt:
            type: float
            nullable: false
            column: montant_total_ht
        tvaTotal:
            type: float
            nullable: false
            column: tva_total
        montantTotalTtc:
            type: float
            nullable: false
            column: montant_total_ttc
        numeroCommercial:
            type: integer
            unsigned: false
            nullable: false
            column: numero_commercial
        paiement:
            type: text
            nullable: false
        quantiteTotale:
            type: integer
            unsigned: false
            nullable: false
            column: quantite_totale
        dateFactureInversee:
            type: text
            nullable: false
            column: date_facture_inversee
        escompte:
            type: float
            nullable: false
        factureAcquittee:
            type: float
            nullable: false
            column: facture_acquittee
        numeroCheque:
            type: text
            nullable: false
            column: numero_cheque
        avoir:
            type: float
            nullable: false
        divers:
            type: integer
            unsigned: false
            nullable: false
            column: divers                
    lifecycleCallbacks: {  }
