IFppo\CommerceBundle\Entity\StatsSageFraisTransportMois:
    type: entity
    table: StatsFraisTransportMois
    fields:
        cbMarq:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: cbMarq
            generator:
                strategy: IDENTITY
        cgNum:
            type: string
            length: 13
            fixed: false
            nullable: true
            column: CG_Num
        ecMontant:
            type: decimal
            nullable: true
            column: EC_Montant 
        ecIntitule:
            type: string
            length: 35
            fixed: false
            nullable: true
            column: EC_Intitule           
        ecDate:
            type: string
            unsigned: false
            nullable: true
            column: EC_Date                      
    lifecycleCallbacks: {  }