parameters:
#    i_fppo_previsionnel.example.class: IFppo\PrevisionnelBundle\Example

services:
#    i_fppo_previsionnel.example:
#        class: %i_fppo_previsionnel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
