parameters:
#    i_fppo_test_jeremy.example.class: IFppo\TestJeremy\Bundle\Example

services:
#    i_fppo_test_jeremy.example:
#        class: %i_fppo_test_jeremy.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
